//
//  AvailableThumbnailImagesM.swift
//  Map Map
//
//  Created by Ben Roberts on 11/25/23.
//

struct AvailableThumbnailImagesM {
    let mappin = "mappin"
    let mappinAndEllipse = "mappin.and.ellipse"
    let mappinSlash = "mappin.slash"
    let mappinStyled = "pin.fill"
    let star = "star.fill"
    let arrowUp = "arrowshape.up.fill"
    let arrowDown = "arrowshape.down.fill"
    let arrowLeft = "arrowshape.left.fill"
    let arrowLeftRight = "arrowshape.left.arrowshape.right.fill"
    let arrowRight = "arrowshape.right.fill"
    let arrow2Left = "signpost.left.fill"
    let arrow2LeftRight = "signpost.right.and.left.fill"
    let arrow2Right = "signpost.right.fill"
    let caution = "exclamationmark.triangle.fill"
    let questionmark = "questionmark"
    let exclamationQuestionmark = "exclamationmark.questionmark"
    let exclamationmark = "exclamationmark"
    let info = "info"
    let figureGolf = "figure.golf"
    let figureHunt = "figure.hunting"
    let figureRun = "figure.run"
    let figureStairs = "figure.stairs"
    let figureStretch = "figure.flexibility"
    let figureWalk = "figure.walk"
    let weatherNoLight = "sun.max.trianglebadge.exclamationmark"
    let weatherSnow = "snowflake"
    let weatherWater = "water.waves"
    let fireworks = "fireworks"
    let house = "house.fill"
    let houseLodge = "house.lodge.fill"
    let houseTent = "tent.fill"
    let mountain = "mountain.2.fill"
    let scribble = "scribble.variable"
    let personChain = "person.line.dotted.person.fill"
    let personSlash = "person.slash.fill"
    let backpack = "backpack.fill"
    let flashlight = "flashlight.on.fill"
    let clipboard = "list.bullet.clipboard.fill"
    let ruler = "ruler.fill"
    let camera = "camera.fill"
    let paperAirplane = "paperplane.fill"
    let key = "key.horizontal.fill"
    let chain = "link"
    let trash = "trash.fill"
}
