//
//  MeasurementEditorV.swift
//  Map Map
//
//  Created by Ben Roberts on 12/15/23.
//

import Bottom_Drawer
import MapKit
import SwiftUI

struct MeasurementEditorV: View {
    /// Information about the background map being plotted on top of.
    @Environment(BackgroundMapDetailsM.self) var backgroundMapDetails
    /// All available MapMaps.
    @FetchRequest(sortDescriptors: []) var mapMaps: FetchedResults<MapMap>
    /// Measurement to edit.
    @FetchRequest(sortDescriptors: []) var measurements: FetchedResults<MapMeasurementCoordinate>
    /// Managed object context the measurement is stored in.
    @Environment(\.managedObjectContext) private var moc
    /// Real-world distance between the start and end points.
    @State private var distance: Measurement<UnitLength> = Measurement(value: .zero, unit: .meters)
    /// Screen-space position of the measuring point.
    @State private var startingPos: CGSize = .zero
    /// Screen-space position of the ending point.
    @State private var endingPos: CGSize = .zero
    /// Track if dragging is currently happening.
    @State private var isDragging: Bool = false
    
    @State private var selectedMeasurement: MapMeasurementCoordinate?
    
    @State private var handlePositions: [MapMeasurementCoordinate : CGSize] = [:]
    
    @Binding var editing: Editor
    /// Map proxy generated by a MapReader.
    let mapContext: MapProxy
    
    /// Basic orientation and positioning for a line
    enum Orientation {
        case leftVertical
        case rightVertical
        case topHorizontal
        case bottomHorizontal
    }
    
    /// Drag gesture for creating a line from scratch.
    var drawGesture: some Gesture {
        DragGesture(coordinateSpace: .global)
            .onChanged { update in
                if !isDragging {
                    startingPos = CGSize(cgPoint: update.startLocation)
                    isDragging = true
                }
                endingPos = CGSize(cgPoint: update.location)
                guard let startingCoord = mapContext.convert(CGPoint(size: startingPos), from: .global),
                      let endingCoord = mapContext.convert(CGPoint(size: endingPos), from: .global)
                else { return }
                let startingLoc = CLLocation(latitude: startingCoord.latitude, longitude: startingCoord.longitude)
                let endingLoc = CLLocation(latitude: endingCoord.latitude, longitude: endingCoord.longitude)
                self.distance = Measurement(value: endingLoc.distance(from: startingLoc), unit: .meters)
            }
            .onEnded { _ in
                isDragging = false
                guard let startingCoord = mapContext.convert(CGPoint(size: startingPos), from: .global),
                      let endingCoord = mapContext.convert(CGPoint(size: endingPos), from: .global)
                else { return }
                let starting = MapMeasurementCoordinate(coordinate: startingCoord, insertInto: moc)
                let ending = MapMeasurementCoordinate(coordinate: endingCoord, insertInto: moc)
                starting.addToNeighbors(ending)
                selectedMeasurement = ending
                startingPos = .zero
                endingPos = .zero
                cleanupMeasurements()
            }
    }
    
    var body: some View {
        GeometryReader { _ in
            ZStack {
                Color.black
                    .opacity(0.5)
                    .ignoresSafeArea()
                    .gesture(drawGesture)
                if endingPos != startingPos {
                    ZStack {
                        Line(startingPos: startingPos, endingPos: endingPos)
                            .stroke(style: StrokeStyle(lineWidth: 5, lineCap: .round))
                            .shadow(radius: 2)
                            .lineLabel(startingPos: CGPoint(size: startingPos), endingPos: CGPoint(size: endingPos), distance: distance)
                        HandleV(position: $startingPos)
                        HandleV(position: $endingPos, color: .highlightBlue)
                    }
                    .ignoresSafeArea()
                }
                
                ForEach(measurements) { measurement in
                    Button {
                        selectedMeasurement = measurement
                    } label: {
                        HandleV(
                            position: binding(for: measurement), 
                            color: selectedMeasurement == measurement ? Color.highlightBlue : HandleV.defaultColor,
                            deferPosition: true
                        )
                    }
                    .position(
                        x: handlePositions[measurement]?.width ?? .zero,
                        y: handlePositions[measurement]?.height ?? .zero
                    )
                }
                .ignoresSafeArea()
                
                BottomDrawer(verticalDetents: [.content], horizontalDetents: [.center], shortCardSize: 350) { _ in
                    VStack {
                        HStack {
                            // Done button
                            Button {
                                editing = .nothing
                                cleanupMeasurements()
                                try? moc.save()
                            } label: {
                                Text("Done")
                                    .bigButton(backgroundColor: .blue)
                            }
                            
                            // Cancel button
                            Button(action: {
                                editing = .nothing
                                moc.reset()
                            }, label: {
                                Text("Cancel")
                                    .bigButton(backgroundColor: .gray)
                            })
                            
                            // Delete button
                            Button( action: {
                                guard let selectedMeasurement = selectedMeasurement
                                else { return }
                                moc.delete(selectedMeasurement)
                                self.selectedMeasurement = nil
                                try? moc.save()
                            }, label: {
                                Text("Delete")
                                    .bigButton(backgroundColor: .red.opacity(selectedMeasurement != nil ? 1 : 0.5))
                            })
                            .disabled(selectedMeasurement == nil)
                        }
                    }
                }
            }
        }
        .onAppear { generateSSHandlePositions() }
        .onReceive(NotificationCenter.default.publisher(for: .NSManagedObjectContextObjectsDidChange)) { _ in
            generateSSHandlePositions()
        }
        .onReceive(NotificationCenter.default.publisher(for: .NSManagedObjectContextDidSave)) { _ in
            cleanupMeasurements()
        }
    }
    
    func generateSSHandlePositions() {
        var handlePositions: [MapMeasurementCoordinate : CGSize] = [:]
        
        for measurement in measurements {
            guard let ssPosition = mapContext.convert(measurement.coordinates, to: .global)
            else { continue }
            handlePositions[measurement] = CGSize(cgPoint: ssPosition)
        }
        self.handlePositions = handlePositions
    }
    
    func binding(for key: MapMeasurementCoordinate) -> Binding<CGSize> {
        Binding<CGSize>(
            get: { self.handlePositions[key] ?? .zero },
            set: {
                guard let mapCoords = mapContext.convert(CGPoint(size: $0), from: .global)
                else { return }
                self.handlePositions[key] = $0
                key.coordinates = mapCoords
                self.selectedMeasurement = key
            }
        )
    }
    
    func cleanupMeasurements() {
        for measurement in measurements where measurement.formattedNeighbors.count == .zero {
            moc.delete(measurement)
        }
    }
}
