//
//  MapMapEditorV.swift
//  Map Map
//
//  Created by Ben Roberts on 4/30/24.
//

import MapKit
import SwiftUI

struct MapMapMapDisplayableEditorV: View {
    @ObservedObject var mapMap: MapMap
    @State var mapMapPosition: CGRect = .zero
    @Environment(MapDetailsM.self) var mapDetails
    
    var body: some View {
        MapDisplayableEditorV(editing: mapMap, actionButtons: []) {
            GeometryReader { geo in
                MapMapV(mapMap, imageType: .image)
                    .onViewResizes { mapMapPosition = CGRect(origin: CGPoint(size: geo.size / 2), size: $1) }
                    .frame(width: geo.size.width * 0.75, height: geo.size.height * 0.75)
                    .opacity(0.5)
                    .allowsHitTesting(false)
                    .position(x: geo.frame(in: .global).midX, y: geo.frame(in: .global).midY)
                    .offset(y: -7)
            }
        } additionalSaveAction: {
            updateMapMapInfo()
        }
    }
    
    /// Determine all Markers that overlap a given MapMap
    /// - Parameters:
    ///   - mapMap: MapMap to check Marker positions against.
    ///   - mapDetails: Details about the map.
    ///   - mapContext: A `MapProxy` that is generated by a `MapReader` to allow for mapping of lat/long coordinates to screen-space.
    /// - Returns: If the MapMap's position in screen-space was not found, then nil is returned.
    /// Otherwise, all available Markers are returned.
    public func mapMapOverMarkers(_ mapMapImage: MapMapImage) -> [Marker]? {
        guard let mapContext = mapDetails.mapProxy,
              let mapMapBounds = MapV.generateMapMapRotatedConvexHull(
                mapMapImage: mapMapImage,
                mapDetails: mapDetails,
                mapContext: mapContext
              )?.cgPath
        else { return nil }
        var markers: [Marker] = []
        
        for marker in markers {
            if let markerPosition = mapContext.convert(marker.coordinate, to: .global) {
                let markerBounds = MarkerEditorV.generateMarkerBoundingBox(markerPosition: markerPosition)
                if mapMapBounds.intersects(markerBounds) {
                    markers.append(marker)
                }
            }
        }
        return markers
    }
    
    /// Updates Map Map information based on the current state of the editor.
    private func updateMapMapInfo() {
        mapMap.coordinate = mapDetails.region.center
        mapMap.mapRotation = -mapDetails.mapCamera.heading
        mapMap.scale = mapMapPosition.width * mapDetails.mapCamera.distance
        mapMap.mapDistance = mapDetails.mapCamera.distance
        mapMap.endEditing()
        mapMap.isSetup = true
        if let mapMapImage = mapMap.activeImage,
            let overlappingMarkers = mapMapOverMarkers(mapMapImage) {
            for marker in mapMap.unwrappedMarkers { mapMap.removeFromMarkers(marker) } // Remove MapMap from all Markers
            for marker in overlappingMarkers { mapMap.addToMarkers(marker) } // Add MapMap to all
        }
    }
}
